# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pybingo',
                'doc_host': 'https://davidweinberg.github.io',
                'git_url': 'https://github.com/davidweinberg/pybingo',
                'lib_path': 'pybingo'},
  'syms': { 'pybingo.BingoCard': { 'pybingo.BingoCard.BingoCard': ('bingogame.html#bingocard', 'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.__init__': ('bingogame.html#bingocard.__init__', 'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.__str__': ('bingogame.html#bingocard.__str__', 'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.checkBingo': ( 'bingogame.html#bingocard.checkbingo',
                                                                               'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.loadCard': ('bingogame.html#bingocard.loadcard', 'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.sumBoard': ('bingogame.html#bingocard.sumboard', 'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.updateBingo': ( 'bingogame.html#bingocard.updatebingo',
                                                                                'pybingo/BingoCard.py'),
                                   'pybingo.BingoCard.BingoCard.updateCard': ( 'bingogame.html#bingocard.updatecard',
                                                                               'pybingo/BingoCard.py')}}}
