# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pybingo',
                'doc_host': 'https://davidweinberg.github.io',
                'git_url': 'https://github.com/davidweinberg/pybingo',
                'lib_path': 'pybingo'},
  'syms': {'pybingo.core': {'pybingo.core.foo': ('core.html#foo', 'pybingo/core.py')}}}
